export const CHAT_USERS_LOADING = "CHAT_USERS_LOADING";
export const CHAT_USERS_SUCCESS = "CHAT_USERS_SUCCESS";
export const CHAT_USERS_ERROR = "CHAT_USERS_ERROR";
export const CHAT_USERS_RESET = "CHAT_USERS_RESET";

export const ACTIVE_USERS_LOADING = "ACTIVE_USERS_LOADING";
export const ACTIVE_USERS_SUCCESS = "ACTIVE_USERS_SUCCESS";
export const ACTIVE_USERS_ERROR = "ACTIVE_USERS_ERROR";
export const ACTIVE_USERS_RESET = "ACTIVE_USERS_RESET";

export const CREATE_CHATID_SUCCESS = "CREATE_CHATID_SUCCESS";

export const SET_ACTIVE_ROOM_ID = "SET_ACTIVE_ROOM_ID";
export const RESET_ACTIVE_ROOM_ID = "RESET_ACTIVE_ROOM_ID";
