export const POST_REQUEST_SUCCESS = "POST_REQUEST_SUCCESS";
export const POST_REQUEST_LOADING = "POST_REQUEST_LOADING";
export const POST_REQUEST_RESET = "POST_REQUEST_RESET";
export const POST_REQUEST_ERROR = "POST_REQUEST_ERROR";

export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_LOADING = "DELETE_REQUEST_LOADING";
export const DELETE_REQUEST_RESET = "DELETE_REQUEST_RESET";
export const DELETE_REQUEST_ERROR = "DELETE_REQUEST_ERROR";

export const POST_FAIL = "POST_FAIL";
export const POST_LOADING = "POST_LOADING";
export const POST_ERROR = "POST_ERROR";
export const POST_SUCCESS = "POST_SUCCESS";

export const POST_METADATA_SET = "POST_METADATA_SET";
